from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from media_server_api.models.base_model import Model
from media_server_api.models.date_range_conf_param import DateRangeConfParam
from media_server_api.models.date_time_range_conf_param import DateTimeRangeConfParam
from media_server_api.models.integer_range_conf_param import IntegerRangeConfParam
from media_server_api.models.range_conf_param import RangeConfParam
from media_server_api import util

from media_server_api.models.date_range_conf_param import DateRangeConfParam  # noqa: E501
from media_server_api.models.date_time_range_conf_param import DateTimeRangeConfParam  # noqa: E501
from media_server_api.models.integer_range_conf_param import IntegerRangeConfParam  # noqa: E501
from media_server_api.models.range_conf_param import RangeConfParam  # noqa: E501

class ConfParamDescription(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, min_value=None, max_value=None):  # noqa: E501
        """ConfParamDescription - a model defined in OpenAPI

        :param min_value: The min_value of this ConfParamDescription.  # noqa: E501
        :type min_value: datetime
        :param max_value: The max_value of this ConfParamDescription.  # noqa: E501
        :type max_value: date
        """
        self.openapi_types = {
            'min_value': datetime,
            'max_value': date
        }

        self.attribute_map = {
            'min_value': 'minValue',
            'max_value': 'maxValue'
        }

        self._min_value = min_value
        self._max_value = max_value

    @classmethod
    def from_dict(cls, dikt) -> 'ConfParamDescription':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfParam_description of this ConfParamDescription.  # noqa: E501
        :rtype: ConfParamDescription
        """
        return util.deserialize_model(dikt, cls)

    @property
    def min_value(self) -> datetime:
        """Gets the min_value of this ConfParamDescription.


        :return: The min_value of this ConfParamDescription.
        :rtype: datetime
        """
        return self._min_value

    @min_value.setter
    def min_value(self, min_value: datetime):
        """Sets the min_value of this ConfParamDescription.


        :param min_value: The min_value of this ConfParamDescription.
        :type min_value: datetime
        """

        self._min_value = min_value

    @property
    def max_value(self) -> date:
        """Gets the max_value of this ConfParamDescription.


        :return: The max_value of this ConfParamDescription.
        :rtype: date
        """
        return self._max_value

    @max_value.setter
    def max_value(self, max_value: date):
        """Sets the max_value of this ConfParamDescription.


        :param max_value: The max_value of this ConfParamDescription.
        :type max_value: date
        """

        self._max_value = max_value
