from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from media_server_api.models.base_model import Model
from media_server_api import util


class DateRangeSLO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, min_value=None, max_value=None, min_range=None, max_range=None):  # noqa: E501
        """DateRangeSLO - a model defined in OpenAPI

        :param min_value: The min_value of this DateRangeSLO.  # noqa: E501
        :type min_value: date
        :param max_value: The max_value of this DateRangeSLO.  # noqa: E501
        :type max_value: date
        :param min_range: The min_range of this DateRangeSLO.  # noqa: E501
        :type min_range: date
        :param max_range: The max_range of this DateRangeSLO.  # noqa: E501
        :type max_range: date
        """
        self.openapi_types = {
            'min_value': date,
            'max_value': date,
            'min_range': date,
            'max_range': date
        }

        self.attribute_map = {
            'min_value': 'minValue',
            'max_value': 'maxValue',
            'min_range': 'minRange',
            'max_range': 'maxRange'
        }

        self._min_value = min_value
        self._max_value = max_value
        self._min_range = min_range
        self._max_range = max_range

    @classmethod
    def from_dict(cls, dikt) -> 'DateRangeSLO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DateRangeSLO of this DateRangeSLO.  # noqa: E501
        :rtype: DateRangeSLO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def min_value(self) -> date:
        """Gets the min_value of this DateRangeSLO.


        :return: The min_value of this DateRangeSLO.
        :rtype: date
        """
        return self._min_value

    @min_value.setter
    def min_value(self, min_value: date):
        """Sets the min_value of this DateRangeSLO.


        :param min_value: The min_value of this DateRangeSLO.
        :type min_value: date
        """

        self._min_value = min_value

    @property
    def max_value(self) -> date:
        """Gets the max_value of this DateRangeSLO.


        :return: The max_value of this DateRangeSLO.
        :rtype: date
        """
        return self._max_value

    @max_value.setter
    def max_value(self, max_value: date):
        """Sets the max_value of this DateRangeSLO.


        :param max_value: The max_value of this DateRangeSLO.
        :type max_value: date
        """

        self._max_value = max_value

    @property
    def min_range(self) -> date:
        """Gets the min_range of this DateRangeSLO.


        :return: The min_range of this DateRangeSLO.
        :rtype: date
        """
        return self._min_range

    @min_range.setter
    def min_range(self, min_range: date):
        """Sets the min_range of this DateRangeSLO.


        :param min_range: The min_range of this DateRangeSLO.
        :type min_range: date
        """
        if min_range is None:
            raise ValueError("Invalid value for `min_range`, must not be `None`")  # noqa: E501

        self._min_range = min_range

    @property
    def max_range(self) -> date:
        """Gets the max_range of this DateRangeSLO.


        :return: The max_range of this DateRangeSLO.
        :rtype: date
        """
        return self._max_range

    @max_range.setter
    def max_range(self, max_range: date):
        """Sets the max_range of this DateRangeSLO.


        :param max_range: The max_range of this DateRangeSLO.
        :type max_range: date
        """
        if max_range is None:
            raise ValueError("Invalid value for `max_range`, must not be `None`")  # noqa: E501

        self._max_range = max_range
