from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from media_server_api.models.base_model import Model
from media_server_api import util


class IntegerRangeSLO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, min_value=None, max_value=None, min_range=None, max_range=None):  # noqa: E501
        """IntegerRangeSLO - a model defined in OpenAPI

        :param min_value: The min_value of this IntegerRangeSLO.  # noqa: E501
        :type min_value: int
        :param max_value: The max_value of this IntegerRangeSLO.  # noqa: E501
        :type max_value: int
        :param min_range: The min_range of this IntegerRangeSLO.  # noqa: E501
        :type min_range: int
        :param max_range: The max_range of this IntegerRangeSLO.  # noqa: E501
        :type max_range: int
        """
        self.openapi_types = {
            'min_value': int,
            'max_value': int,
            'min_range': int,
            'max_range': int
        }

        self.attribute_map = {
            'min_value': 'minValue',
            'max_value': 'maxValue',
            'min_range': 'minRange',
            'max_range': 'maxRange'
        }

        self._min_value = min_value
        self._max_value = max_value
        self._min_range = min_range
        self._max_range = max_range

    @classmethod
    def from_dict(cls, dikt) -> 'IntegerRangeSLO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IntegerRangeSLO of this IntegerRangeSLO.  # noqa: E501
        :rtype: IntegerRangeSLO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def min_value(self) -> int:
        """Gets the min_value of this IntegerRangeSLO.


        :return: The min_value of this IntegerRangeSLO.
        :rtype: int
        """
        return self._min_value

    @min_value.setter
    def min_value(self, min_value: int):
        """Sets the min_value of this IntegerRangeSLO.


        :param min_value: The min_value of this IntegerRangeSLO.
        :type min_value: int
        """

        self._min_value = min_value

    @property
    def max_value(self) -> int:
        """Gets the max_value of this IntegerRangeSLO.


        :return: The max_value of this IntegerRangeSLO.
        :rtype: int
        """
        return self._max_value

    @max_value.setter
    def max_value(self, max_value: int):
        """Sets the max_value of this IntegerRangeSLO.


        :param max_value: The max_value of this IntegerRangeSLO.
        :type max_value: int
        """

        self._max_value = max_value

    @property
    def min_range(self) -> int:
        """Gets the min_range of this IntegerRangeSLO.


        :return: The min_range of this IntegerRangeSLO.
        :rtype: int
        """
        return self._min_range

    @min_range.setter
    def min_range(self, min_range: int):
        """Sets the min_range of this IntegerRangeSLO.


        :param min_range: The min_range of this IntegerRangeSLO.
        :type min_range: int
        """
        if min_range is None:
            raise ValueError("Invalid value for `min_range`, must not be `None`")  # noqa: E501

        self._min_range = min_range

    @property
    def max_range(self) -> int:
        """Gets the max_range of this IntegerRangeSLO.


        :return: The max_range of this IntegerRangeSLO.
        :rtype: int
        """
        return self._max_range

    @max_range.setter
    def max_range(self, max_range: int):
        """Sets the max_range of this IntegerRangeSLO.


        :param max_range: The max_range of this IntegerRangeSLO.
        :type max_range: int
        """
        if max_range is None:
            raise ValueError("Invalid value for `max_range`, must not be `None`")  # noqa: E501

        self._max_range = max_range
