from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from media_server_api.models.base_model import Model
from media_server_api import util


class RangeConfParam(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, min_value=None, max_value=None):  # noqa: E501
        """RangeConfParam - a model defined in OpenAPI

        :param min_value: The min_value of this RangeConfParam.  # noqa: E501
        :type min_value: float
        :param max_value: The max_value of this RangeConfParam.  # noqa: E501
        :type max_value: float
        """
        self.openapi_types = {
            'min_value': float,
            'max_value': float
        }

        self.attribute_map = {
            'min_value': 'minValue',
            'max_value': 'maxValue'
        }

        self._min_value = min_value
        self._max_value = max_value

    @classmethod
    def from_dict(cls, dikt) -> 'RangeConfParam':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RangeConfParam of this RangeConfParam.  # noqa: E501
        :rtype: RangeConfParam
        """
        return util.deserialize_model(dikt, cls)

    @property
    def min_value(self) -> float:
        """Gets the min_value of this RangeConfParam.


        :return: The min_value of this RangeConfParam.
        :rtype: float
        """
        return self._min_value

    @min_value.setter
    def min_value(self, min_value: float):
        """Sets the min_value of this RangeConfParam.


        :param min_value: The min_value of this RangeConfParam.
        :type min_value: float
        """

        self._min_value = min_value

    @property
    def max_value(self) -> float:
        """Gets the max_value of this RangeConfParam.


        :return: The max_value of this RangeConfParam.
        :rtype: float
        """
        return self._max_value

    @max_value.setter
    def max_value(self, max_value: float):
        """Sets the max_value of this RangeConfParam.


        :param max_value: The max_value of this RangeConfParam.
        :type max_value: float
        """

        self._max_value = max_value
