inputSpec: ServiceAPIExample.yml
outputDir: media_server_api_implementation
generatorName: python-flask
controllerPackage: api_controllers
defaultController: api_controller
featureCORS: true
packageName: media_server_api
packageVersion: 0.0.1
serverPort: 8080