services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: media-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - ./jellyfin_conf:/config
      - ./jellyfin_data:/data
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
  mosquitto:
    image: eclipse-mosquitto
    container_name: telemetry-broker
    volumes:
      - ./telemetry_conf:/mosquitto/config
    ports:
      - 1883:1883
  influxdb:
    image: influxdb:2
    container_name: telemetry-db
    ports:
      - 8086:8086
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
      - ./influxdb_conf:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=tuwiendsg
      - DOCKER_INFLUXDB_INIT_PASSWORD=tuwiendsg
      - DOCKER_INFLUXDB_INIT_ORG=tuwien
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=december
  qos-hook:
    build:
      context: mqtt_hook
      dockerfile: Dockerfile
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_CLIENT_ID=media-server-api
      - MQTT_TOPIC=autowatcher/reporting
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=december
      - INFLUX_ORG=tuwien
      - INFLUX_BUCKET=telemetry
      - CONFIG_FILE=/confs/jellyfin-qos.json
    volumes:
      -  ./hook_confs:/confs:ro
    depends_on:
      - influxdb
      - mosquitto
  nrg-hook:
    build:
      context: mqtt_hook
      dockerfile: Dockerfile
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=december
      - INFLUX_ORG=tuwien
      - INFLUX_BUCKET=telemetry
      - MQTT_CLIENT_ID=nrg-hook
      - MQTT_TOPIC=energy/+/SENSOR
      - CONFIG_FILE=/confs/delock-energy.json
    volumes:
      - ./hook_confs:/confs:ro
    depends_on:
      - influxdb
      - mosquitto
  cpu-freq-hook:
    build:
      context: mqtt_hook
      dockerfile: Dockerfile
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=december
      - INFLUX_ORG=tuwien
      - INFLUX_BUCKET=telemetry
      - MQTT_CLIENT_ID=cpu-freq-hook
      - MQTT_TOPIC=systemlemetry/CPUFreq
      - CONFIG_FILE=/confs/systemlemetry-hook-cpu-freq.json
    volumes:
      - ./hook_confs:/confs:ro
    depends_on:
      - influxdb
      - mosquitto
  cpu-pctg-hook:
    build:
      context: mqtt_hook
      dockerfile: Dockerfile
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=december
      - INFLUX_ORG=tuwien
      - INFLUX_BUCKET=telemetry
      - MQTT_CLIENT_ID=cpu-pctg-hook
      - MQTT_TOPIC=systemlemetry/CPUPctg
      - CONFIG_FILE=/confs/systemlemetry-hook-cpu-pctg.json
    volumes:
      - ./hook_confs:/confs:ro
    depends_on:
      - influxdb
      - mosquitto
  memory-hook:
    build:
      context: mqtt_hook
      dockerfile: Dockerfile
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=december
      - INFLUX_ORG=tuwien
      - INFLUX_BUCKET=telemetry
      - MQTT_CLIENT_ID=memory-hook
      - MQTT_TOPIC=systemlemetry/Memory
      - CONFIG_FILE=/confs/systemlemetry-hook-memory.json
    volumes:
      - ./hook_confs:/confs:ro
    depends_on:
      - influxdb
      - mosquitto
  network-hook:
    build:
      context: mqtt_hook
      dockerfile: Dockerfile
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=december
      - INFLUX_ORG=tuwien
      - INFLUX_BUCKET=telemetry
      - MQTT_CLIENT_ID=network-hook
      - MQTT_TOPIC=systemlemetry/Network
      - CONFIG_FILE=/confs/systemlemetry-hook-network.json
    volumes:
      - ./hook_confs:/confs:ro
    depends_on:
      - influxdb
      - mosquitto
  proc-hook:
    build:
      context: mqtt_hook
      dockerfile: Dockerfile
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=december
      - INFLUX_ORG=tuwien
      - INFLUX_BUCKET=telemetry
      - MQTT_CLIENT_ID=proc-hook
      - MQTT_TOPIC=systemlemetry/Processes
      - CONFIG_FILE=/confs/systemlemetry-hook-proc.json
    volumes:
      - ./hook_confs:/confs:ro
    depends_on:
      - influxdb
      - mosquitto
  temp-hook:
    build:
      context: mqtt_hook
      dockerfile: Dockerfile
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=december
      - INFLUX_ORG=tuwien
      - INFLUX_BUCKET=telemetry
      - MQTT_CLIENT_ID=temp-hook
      - MQTT_TOPIC=systemlemetry/Temperatures
      - CONFIG_FILE=/confs/systemlemetry-hook-temp.json
    volumes:
      - ./hook_confs:/confs:ro
    depends_on:
      - influxdb
      - mosquitto
  service-api:
    build:
      context: service_api
      dockerfile: Dockerfile
    environment:
      - SLO_FILE=/confs/qos.json
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=december
      - INFLUX_ORG=tuwien
      - INFLUX_BUCKET=telemetry
      - JELLYFIN_URL=http://jellyfin:8096
      - JELLYFIN_API_KEY=f040763a24b74e99bae5f30d15215c68
      - WORKERS=1
      - LISTEN_HOST=0.0.0.0
      - LOG_LEVEL=debug
    ports:
      - 8080:80
    volumes:
      - ./slo_confs:/confs:ro
    depends_on:
      - jellyfin
      - influxdb