from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from media_server_api.models.base_model import Model
from media_server_api import util


class ConfParamType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    BOOLEAN = 'boolean'
    BYTE = 'byte'
    BINARY = 'binary'
    RANGE = 'range'
    INTEGER_RANGE = 'integer_range'
    DATE_RANGE = 'date_range'
    DATETIME_RANGE = 'datetime_range'
    NUMERIC_VALUE_LIST = 'numeric_value_list'
    INTEGER_VALUE_LIST = 'integer_value_list'
    STRING_VALUE_LIST = 'string_value_list'
    DATE_VALUE_LIST = 'date_value_list'
    DATETIME_VALUE_LIST = 'datetime_value_list'
    BYTE_VALUE_LIST = 'byte_value_list'
    BINARY_VALUE_LIST = 'binary_value_list'
    def __init__(self):  # noqa: E501
        """ConfParamType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ConfParamType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfParamType of this ConfParamType.  # noqa: E501
        :rtype: ConfParamType
        """
        return util.deserialize_model(dikt, cls)
