from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from media_server_api.models.base_model import Model
from media_server_api.models.conf_param_description_value_list_inner import ConfParamDescriptionValueListInner
from media_server_api.models.slo_description_max_value import SLODescriptionMaxValue
from media_server_api.models.slo_description_min_value import SLODescriptionMinValue
from media_server_api import util

from media_server_api.models.conf_param_description_value_list_inner import ConfParamDescriptionValueListInner  # noqa: E501
from media_server_api.models.slo_description_max_value import SLODescriptionMaxValue  # noqa: E501
from media_server_api.models.slo_description_min_value import SLODescriptionMinValue  # noqa: E501

class ConfParamDescription(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, min_value=None, max_value=None, value_list=None):  # noqa: E501
        """ConfParamDescription - a model defined in OpenAPI

        :param min_value: The min_value of this ConfParamDescription.  # noqa: E501
        :type min_value: SLODescriptionMinValue
        :param max_value: The max_value of this ConfParamDescription.  # noqa: E501
        :type max_value: SLODescriptionMaxValue
        :param value_list: The value_list of this ConfParamDescription.  # noqa: E501
        :type value_list: List[ConfParamDescriptionValueListInner]
        """
        self.openapi_types = {
            'min_value': SLODescriptionMinValue,
            'max_value': SLODescriptionMaxValue,
            'value_list': List[ConfParamDescriptionValueListInner]
        }

        self.attribute_map = {
            'min_value': 'minValue',
            'max_value': 'maxValue',
            'value_list': 'valueList'
        }

        self._min_value = min_value
        self._max_value = max_value
        self._value_list = value_list

    @classmethod
    def from_dict(cls, dikt) -> 'ConfParamDescription':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfParamDescription of this ConfParamDescription.  # noqa: E501
        :rtype: ConfParamDescription
        """
        return util.deserialize_model(dikt, cls)

    @property
    def min_value(self) -> SLODescriptionMinValue:
        """Gets the min_value of this ConfParamDescription.


        :return: The min_value of this ConfParamDescription.
        :rtype: SLODescriptionMinValue
        """
        return self._min_value

    @min_value.setter
    def min_value(self, min_value: SLODescriptionMinValue):
        """Sets the min_value of this ConfParamDescription.


        :param min_value: The min_value of this ConfParamDescription.
        :type min_value: SLODescriptionMinValue
        """

        self._min_value = min_value

    @property
    def max_value(self) -> SLODescriptionMaxValue:
        """Gets the max_value of this ConfParamDescription.


        :return: The max_value of this ConfParamDescription.
        :rtype: SLODescriptionMaxValue
        """
        return self._max_value

    @max_value.setter
    def max_value(self, max_value: SLODescriptionMaxValue):
        """Sets the max_value of this ConfParamDescription.


        :param max_value: The max_value of this ConfParamDescription.
        :type max_value: SLODescriptionMaxValue
        """

        self._max_value = max_value

    @property
    def value_list(self) -> List[ConfParamDescriptionValueListInner]:
        """Gets the value_list of this ConfParamDescription.


        :return: The value_list of this ConfParamDescription.
        :rtype: List[ConfParamDescriptionValueListInner]
        """
        return self._value_list

    @value_list.setter
    def value_list(self, value_list: List[ConfParamDescriptionValueListInner]):
        """Sets the value_list of this ConfParamDescription.


        :param value_list: The value_list of this ConfParamDescription.
        :type value_list: List[ConfParamDescriptionValueListInner]
        """
        if value_list is not None and len(value_list) < 1:
            raise ValueError("Invalid value for `value_list`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._value_list = value_list
