from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from media_server_api.models.base_model import Model
from media_server_api import util


class ConfParamValue(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """ConfParamValue - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ConfParamValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfParam_value of this ConfParamValue.  # noqa: E501
        :rtype: ConfParamValue
        """
        return util.deserialize_model(dikt, cls)
