from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from media_server_api.models.base_model import Model
from media_server_api import util


class RangeSLO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, min_value=None, max_value=None, min_range=None, max_range=None):  # noqa: E501
        """RangeSLO - a model defined in OpenAPI

        :param min_value: The min_value of this RangeSLO.  # noqa: E501
        :type min_value: float
        :param max_value: The max_value of this RangeSLO.  # noqa: E501
        :type max_value: float
        :param min_range: The min_range of this RangeSLO.  # noqa: E501
        :type min_range: float
        :param max_range: The max_range of this RangeSLO.  # noqa: E501
        :type max_range: float
        """
        self.openapi_types = {
            'min_value': float,
            'max_value': float,
            'min_range': float,
            'max_range': float
        }

        self.attribute_map = {
            'min_value': 'minValue',
            'max_value': 'maxValue',
            'min_range': 'minRange',
            'max_range': 'maxRange'
        }

        self._min_value = min_value
        self._max_value = max_value
        self._min_range = min_range
        self._max_range = max_range

    @classmethod
    def from_dict(cls, dikt) -> 'RangeSLO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RangeSLO of this RangeSLO.  # noqa: E501
        :rtype: RangeSLO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def min_value(self) -> float:
        """Gets the min_value of this RangeSLO.


        :return: The min_value of this RangeSLO.
        :rtype: float
        """
        return self._min_value

    @min_value.setter
    def min_value(self, min_value: float):
        """Sets the min_value of this RangeSLO.


        :param min_value: The min_value of this RangeSLO.
        :type min_value: float
        """

        self._min_value = min_value

    @property
    def max_value(self) -> float:
        """Gets the max_value of this RangeSLO.


        :return: The max_value of this RangeSLO.
        :rtype: float
        """
        return self._max_value

    @max_value.setter
    def max_value(self, max_value: float):
        """Sets the max_value of this RangeSLO.


        :param max_value: The max_value of this RangeSLO.
        :type max_value: float
        """

        self._max_value = max_value

    @property
    def min_range(self) -> float:
        """Gets the min_range of this RangeSLO.


        :return: The min_range of this RangeSLO.
        :rtype: float
        """
        return self._min_range

    @min_range.setter
    def min_range(self, min_range: float):
        """Sets the min_range of this RangeSLO.


        :param min_range: The min_range of this RangeSLO.
        :type min_range: float
        """
        if min_range is None:
            raise ValueError("Invalid value for `min_range`, must not be `None`")  # noqa: E501

        self._min_range = min_range

    @property
    def max_range(self) -> float:
        """Gets the max_range of this RangeSLO.


        :return: The max_range of this RangeSLO.
        :rtype: float
        """
        return self._max_range

    @max_range.setter
    def max_range(self, max_range: float):
        """Sets the max_range of this RangeSLO.


        :param max_range: The max_range of this RangeSLO.
        :type max_range: float
        """
        if max_range is None:
            raise ValueError("Invalid value for `max_range`, must not be `None`")  # noqa: E501

        self._max_range = max_range
