from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from media_server_api.models.base_model import Model
from media_server_api.models.slo_description import SLODescription
from media_server_api.models.slo_type import SLOType
from media_server_api import util

from media_server_api.models.slo_description import SLODescription  # noqa: E501
from media_server_api.models.slo_type import SLOType  # noqa: E501

class SLO(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, type=None, description=None):  # noqa: E501
        """SLO - a model defined in OpenAPI

        :param id: The id of this SLO.  # noqa: E501
        :type id: str
        :param name: The name of this SLO.  # noqa: E501
        :type name: str
        :param type: The type of this SLO.  # noqa: E501
        :type type: SLOType
        :param description: The description of this SLO.  # noqa: E501
        :type description: SLODescription
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'type': SLOType,
            'description': SLODescription
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'type': 'type',
            'description': 'description'
        }

        self._id = id
        self._name = name
        self._type = type
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'SLO':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SLO of this SLO.  # noqa: E501
        :rtype: SLO
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this SLO.


        :return: The id of this SLO.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this SLO.


        :param id: The id of this SLO.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and len(id) < 1:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `1`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this SLO.


        :return: The name of this SLO.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this SLO.


        :param name: The name of this SLO.
        :type name: str
        """
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def type(self) -> SLOType:
        """Gets the type of this SLO.


        :return: The type of this SLO.
        :rtype: SLOType
        """
        return self._type

    @type.setter
    def type(self, type: SLOType):
        """Sets the type of this SLO.


        :param type: The type of this SLO.
        :type type: SLOType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def description(self) -> SLODescription:
        """Gets the description of this SLO.


        :return: The description of this SLO.
        :rtype: SLODescription
        """
        return self._description

    @description.setter
    def description(self, description: SLODescription):
        """Sets the description of this SLO.


        :param description: The description of this SLO.
        :type description: SLODescription
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description
