from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from media_server_api.models.base_model import Model
from media_server_api.models.slo_description_max_range import SLODescriptionMaxRange
from media_server_api.models.slo_description_max_value import SLODescriptionMaxValue
from media_server_api.models.slo_description_min_value import SLODescriptionMinValue
from media_server_api.models.slo_description_target import SLODescriptionTarget
from media_server_api import util

from media_server_api.models.slo_description_max_range import SLODescriptionMaxRange  # noqa: E501
from media_server_api.models.slo_description_max_value import SLODescriptionMaxValue  # noqa: E501
from media_server_api.models.slo_description_min_value import SLODescriptionMinValue  # noqa: E501
from media_server_api.models.slo_description_target import SLODescriptionTarget  # noqa: E501

class SLODescription(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, min_value=None, max_value=None, min_range=None, max_range=None, target=None):  # noqa: E501
        """SLODescription - a model defined in OpenAPI

        :param min_value: The min_value of this SLODescription.  # noqa: E501
        :type min_value: SLODescriptionMinValue
        :param max_value: The max_value of this SLODescription.  # noqa: E501
        :type max_value: SLODescriptionMaxValue
        :param min_range: The min_range of this SLODescription.  # noqa: E501
        :type min_range: SLODescriptionMinValue
        :param max_range: The max_range of this SLODescription.  # noqa: E501
        :type max_range: SLODescriptionMaxRange
        :param target: The target of this SLODescription.  # noqa: E501
        :type target: SLODescriptionTarget
        """
        self.openapi_types = {
            'min_value': SLODescriptionMinValue,
            'max_value': SLODescriptionMaxValue,
            'min_range': SLODescriptionMinValue,
            'max_range': SLODescriptionMaxRange,
            'target': SLODescriptionTarget
        }

        self.attribute_map = {
            'min_value': 'minValue',
            'max_value': 'maxValue',
            'min_range': 'minRange',
            'max_range': 'maxRange',
            'target': 'target'
        }

        self._min_value = min_value
        self._max_value = max_value
        self._min_range = min_range
        self._max_range = max_range
        self._target = target

    @classmethod
    def from_dict(cls, dikt) -> 'SLODescription':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SLODescription of this SLODescription.  # noqa: E501
        :rtype: SLODescription
        """
        return util.deserialize_model(dikt, cls)

    @property
    def min_value(self) -> SLODescriptionMinValue:
        """Gets the min_value of this SLODescription.


        :return: The min_value of this SLODescription.
        :rtype: SLODescriptionMinValue
        """
        return self._min_value

    @min_value.setter
    def min_value(self, min_value: SLODescriptionMinValue):
        """Sets the min_value of this SLODescription.


        :param min_value: The min_value of this SLODescription.
        :type min_value: SLODescriptionMinValue
        """

        self._min_value = min_value

    @property
    def max_value(self) -> SLODescriptionMaxValue:
        """Gets the max_value of this SLODescription.


        :return: The max_value of this SLODescription.
        :rtype: SLODescriptionMaxValue
        """
        return self._max_value

    @max_value.setter
    def max_value(self, max_value: SLODescriptionMaxValue):
        """Sets the max_value of this SLODescription.


        :param max_value: The max_value of this SLODescription.
        :type max_value: SLODescriptionMaxValue
        """

        self._max_value = max_value

    @property
    def min_range(self) -> SLODescriptionMinValue:
        """Gets the min_range of this SLODescription.


        :return: The min_range of this SLODescription.
        :rtype: SLODescriptionMinValue
        """
        return self._min_range

    @min_range.setter
    def min_range(self, min_range: SLODescriptionMinValue):
        """Sets the min_range of this SLODescription.


        :param min_range: The min_range of this SLODescription.
        :type min_range: SLODescriptionMinValue
        """

        self._min_range = min_range

    @property
    def max_range(self) -> SLODescriptionMaxRange:
        """Gets the max_range of this SLODescription.


        :return: The max_range of this SLODescription.
        :rtype: SLODescriptionMaxRange
        """
        return self._max_range

    @max_range.setter
    def max_range(self, max_range: SLODescriptionMaxRange):
        """Sets the max_range of this SLODescription.


        :param max_range: The max_range of this SLODescription.
        :type max_range: SLODescriptionMaxRange
        """

        self._max_range = max_range

    @property
    def target(self) -> SLODescriptionTarget:
        """Gets the target of this SLODescription.


        :return: The target of this SLODescription.
        :rtype: SLODescriptionTarget
        """
        return self._target

    @target.setter
    def target(self, target: SLODescriptionTarget):
        """Sets the target of this SLODescription.


        :param target: The target of this SLODescription.
        :type target: SLODescriptionTarget
        """

        self._target = target
