from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from media_server_api.models.base_model import Model
from media_server_api import util


class SLODescriptionMaxRange(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """SLODescriptionMaxRange - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SLODescriptionMaxRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SLODescription_maxRange of this SLODescriptionMaxRange.  # noqa: E501
        :rtype: SLODescriptionMaxRange
        """
        return util.deserialize_model(dikt, cls)
