from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from media_server_api.models.base_model import Model
from media_server_api import util


class SLOType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    BOOLEAN = 'boolean'
    RANGE = 'range'
    INTEGER_RANGE = 'integer_range'
    DATE_RANGE = 'date_range'
    DATETIME_RANGE = 'datetime_range'
    TARGET_VALUE = 'target_value'
    INTEGER_TARGET_VALUE = 'integer_target_value'
    STRING_TARGET_VALUE = 'string_target_value'
    DATE_TARGET_VALUE = 'date_target_value'
    DATETIME_TARGET_VALUE = 'datetime_target_value'
    def __init__(self):  # noqa: E501
        """SLOType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SLOType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SLOType of this SLOType.  # noqa: E501
        :rtype: SLOType
        """
        return util.deserialize_model(dikt, cls)
