openapi: 3.0.4
info:
  title: Service API
  version: research-0.2
externalDocs:
  description: Read the paper on this specification
  url: https://doi.org/ADD-THE-DOI-HERE-ONCE-WE-HAVE-IT
servers:
- url: https://apitest:80/v0
tags:
- description: Endpoints related to SLO measurement
  externalDocs:
    description: Read the work on how to use SLOs
    url: https://doi.org/10.1109/SOSE62363.2024.00008
  name: slo
- description: Endpoints related to service configuration
  name: config
paths:
  /config:
    get:
      description: Returns the list of configurable service parameters with their
        definitions and current values.
      operationId: config_discover
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/ConfParam"
                minItems: 1
                type: array
          description: successful operation
        "404":
          description: This service declares no configurable parameters.
      summary: "Discover, describe, and gather configuration."
      tags:
      - config
      x-openapi-router-controller: media_server_api.api_controllers.config_controller
  /config/{confParam}:
    get:
      description: Returns the description and current value of the requested parameter.
      operationId: config_value
      parameters:
      - description: Name of the parameter to describe
        explode: false
        in: path
        name: confParam
        required: true
        schema:
          example: nextBackup
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConfParam"
          description: successful operation
        "404":
          description: The requested parameter does not exist
      summary: Parameter value.
      tags:
      - config
      x-openapi-router-controller: media_server_api.api_controllers.config_controller
    put:
      description: Changes the value of the requested parameter.
      operationId: config_change
      parameters:
      - description: Name of the parameter to describe
        explode: false
        in: path
        name: confParam
        required: true
        schema:
          example: nextBackup
          minLength: 1
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConfParamValue"
      responses:
        "200":
          description: successful operation
        "404":
          description: The requested parameter does not exist
        "400":
          description: Invalid value for the parameter
      summary: Change parameter.
      tags:
      - config
      x-openapi-router-controller: media_server_api.api_controllers.config_controller
  /slos:
    get:
      description: Returns the list of declared SLOs of the service with their definitions
        and current values
      operationId: slo_discover
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/SLO"
                minItems: 1
                type: array
          description: successful operation
        "404":
          description: This service declares no SLOs
      summary: "Discover, describe, and gather values of SLOs."
      tags:
      - slo
      x-openapi-router-controller: media_server_api.api_controllers.slo_controller
  /slos/{sloId}:
    get:
      description: Returns the description and current value of the requested SLO.
      operationId: slo_value
      parameters:
      - description: ID of SLO to describe
        explode: false
        in: path
        name: sloId
        required: true
        schema:
          example: rps
          minLength: 1
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SLO"
          description: successful operation
        "404":
          description: The requested SLO does not exist
      summary: Describe and gather value of an SLO.
      tags:
      - slo
      x-openapi-router-controller: media_server_api.api_controllers.slo_controller
components:
  schemas:
    SLO:
      example:
        name: Requests satisfied per second
        description:
          minValue: 0
          maxValue: 30
          maxRange: 1000
          minRange: 0
          target: true
        id: rps
        type: boolean
        value: 20
      properties:
        id:
          example: rps
          minLength: 1
          title: id
          type: string
        name:
          example: Requests satisfied per second
          minLength: 1
          title: name
          type: string
        type:
          $ref: "#/components/schemas/SLOType"
        value:
          $ref: "#/components/schemas/SLO_value"
        description:
          $ref: "#/components/schemas/SLODescription"
      required:
      - description
      - id
      - type
      title: SLO
      type: object
    SLODescription:
      example:
        minValue: 0
        maxValue: 30
        maxRange: 1000
        minRange: 0
        target: true
      properties:
        minValue:
          $ref: "#/components/schemas/SLODescription_minValue"
        maxValue:
          $ref: "#/components/schemas/SLODescription_maxValue"
        minRange:
          $ref: "#/components/schemas/SLODescription_minValue"
        maxRange:
          $ref: "#/components/schemas/SLODescription_maxRange"
        target:
          $ref: "#/components/schemas/SLODescription_target"
      title: SLODescription
      type: object
    SLOType:
      enum:
      - boolean
      - range
      - integer_range
      - date_range
      - datetime_range
      - target_value
      - integer_target_value
      - string_target_value
      - date_target_value
      - datetime_target_value
      title: SLOType
      type: string
    ConfParam:
      example:
        name: Time for next scheduled backup
        description:
          minValue: 0
          maxValue: 30
          valueList:
          - 0.8008281904610115
          - 0.8008281904610115
        id: nextBackup
        type: boolean
        value: 2015-06-08T10:41:05Z
      properties:
        id:
          example: nextBackup
          minLength: 1
          title: id
          type: string
        name:
          example: Time for next scheduled backup
          minLength: 1
          title: name
          type: string
        type:
          $ref: "#/components/schemas/ConfParamType"
        description:
          $ref: "#/components/schemas/ConfParamDescription"
        value:
          $ref: "#/components/schemas/ConfParam_value"
      required:
      - description
      - id
      - type
      - value
      title: ConfParam
      type: object
    ConfParamType:
      enum:
      - boolean
      - byte
      - binary
      - range
      - integer_range
      - date_range
      - datetime_range
      - numeric_value_list
      - integer_value_list
      - string_value_list
      - date_value_list
      - datetime_value_list
      - byte_value_list
      - binary_value_list
      title: ConfParamType
      type: string
    ConfParamDescription:
      example:
        minValue: 0
        maxValue: 30
        valueList:
        - 0.8008281904610115
        - 0.8008281904610115
      properties:
        minValue:
          $ref: "#/components/schemas/SLODescription_minValue"
        maxValue:
          $ref: "#/components/schemas/SLODescription_maxValue"
        valueList:
          items:
            $ref: "#/components/schemas/ConfParamDescription_valueList_inner"
          minItems: 1
          title: valueList
          type: array
      title: ConfParamDescription
      type: object
    ConfParamValue:
      example:
        value: true
      properties:
        value:
          $ref: "#/components/schemas/SLODescription_target"
      required:
      - value
      title: ConfParamValue
      type: object
    SLO_value:
      example: 20
      oneOf:
      - type: boolean
      - type: number
      - type: string
      title: SLO_value
    SLODescription_minValue:
      example: 0
      oneOf:
      - type: number
      - type: string
      title: SLODescription_minValue
    SLODescription_maxValue:
      example: 30
      oneOf:
      - type: number
      - type: string
      title: SLODescription_maxValue
    SLODescription_maxRange:
      example: 1000
      oneOf:
      - type: number
      - type: string
      title: SLODescription_maxRange
    SLODescription_target:
      oneOf:
      - type: boolean
      - type: number
      - type: string
      title: SLODescription_target
    ConfParam_value:
      example: 2015-06-08T10:41:05Z
      oneOf:
      - type: boolean
      - type: number
      - type: string
      title: ConfParam_value
    ConfParamDescription_valueList_inner:
      oneOf:
      - type: number
      - type: string
      title: ConfParamDescription_valueList_inner
